name: Flutter CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
  
    # Setup Java environment
    - uses: actions/checkout@v1
      name: Installing checkout actions
      
    - uses: actions/setup-java@v1
      name: Installing java
      with:
        java-version: '12.x'
        
        
    # Setup the flutter environment.
    - uses: subosito/flutter-action@v1
      name: Installing flutter
      with:
        flutter-version: '1.12.x' # you can use 1.12
        channel: 'beta' # Currently you have to use beta channel for Flutter web.  # 'dev', 'alpha', default to: 'stable'
        
    # doing flutter commands
    - name: Upgrade CIs copy of flutter
      run: flutter upgrade
      working-directory: ./dummy_flutter_app_1

    - name: Enable Web in flutter
      run: flutter config --enable-web
      working-directory: ./dummy_flutter_app_1
      
      
    - name: Install dependencies for this project
      run: flutter packages get
      working-directory: ./dummy_flutter_app_1
      
    - name: Build Web release for this package
      run: flutter build web
      working-directory: ./dummy_flutter_app_1
      
    - name: Deploy the built artifacts to gh-pages branch
      run: |
        cd ./dummy_flutter_app_1/build/web
        git init
        git config user.name  "my-flutter-ci"
        git config user.email "my-flutter-ci@github.com"
        git remote add secure-origin https://${{ secrets.ACCESS_TOKEN }}@github.com/amogh2019/flutter-starter-1.git
        git checkout -b gh-pages
        git add .
        git commit -m "Updated docs"
        git push --force secure-origin gh-pages
